spring:
  application:
    name: zkMatch

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zkMatch?rewriteBatchedStatements=true&serverTimezone=Asia/Seoul
    username: root
    password: zkMatch

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100

jwt:
  secret: W32i/qpvlu5IGB3zWr4jZQUgQmbpm2thHOqHAOwofCZxn4fOfnFwF3Znd1qTYn72A2eR6aqvIAzrcWkx5wAbMA==
